### ISSUE TITLE
How to reconstruct config format

### ISSUE THREAD

**Issue by rinrinne** [rinrinne/gerrit-rabbitmq-plugin#11]
This is a sub task for #3 .

To support multi uri, existing config format should be reconstructed.
There are some solutions

* Keep existing config
  * subsection
  * virtual section with fragments of files

* Obsolete existing config
  * More structured configuration

**Comment by rinrinne** [comment]
Now superior plan is

* Virtual section with fragments of files
* Existing config file can replace default value on each parameters.
* If no fragments, `DEFAULT` virtual subsection is applied to existing config file
** Keep the same behavior as previous

**Comment by huaxings** [comment]
What is the naming strategy you are considering for the conf file fragments?

**Comment by rinrinne** [comment]
Still not fixed. Perhaps file extension is ".config". basename is free.

**Comment by rinrinne** [comment]
The first implementation is now pushed into branch `dev-3.0`

Please visit if interesting :smiley:

**Comment by huaxings** [comment]
I will compile & build locally and see this change can work with our setup at Sony Mobile. Thank you as always.

**Comment by huaxings** [comment]
Hi, 
"gradlew build -PapiVersion=2.8" was successfully executed and I was able to get the plugin jar binary.
However, when I load it to my test Gerrit which is in version 2.8.5, this plugin fails to being loaded.
```
[2015-02-25 15:25:10,267] WARN  com.google.gerrit.server.plugins.PluginLoader : Cannot load plugin rabbitmq
java.lang.NoClassDefFoundError: com/rabbitmq/client/ShutdownListener
```
I suspect there is other dependents not included/imported.

**Comment by rinrinne** [comment]
Did you deploy plugin jar from `build/libs`? Correct plugin jar is stored in `build/distributions` by `shadowJar` target.

**Comment by huaxings** [comment]
Aha. That solved the problem. I should have looked more. At least I am now able to load it. Thanks.

**Comment by huaxings** [comment]
I confirmed the changes made in dev-3.0. Could you explain me why the configuration files are placed in data/ instead of etc/ where configuration files are usually stored? I read in previous discussion that you were suggesting having a "etc/rabbitmq.d/" to store the fragmented files.  Just curious.

**Comment by rinrinne** [comment]
I found that Gerrit is providing plugin data directory using `@PluginData` annotation
https://gerrit-documentation.storage.googleapis.com/Documentation/2.10/dev-plugins.html#data-directory
So I decided to follow the plugin way which Gerrit recommends.

**Comment by rinrinne** [comment]
`dev-3.0` is now feature freeze. It will be merged into `master` next week if no critical issue.

**Comment by rinrinne** [comment]
By commit cec9936a9f2c, shadow jar location is moved to `build/libs'. Sorry for confusion but here is default in shadow jar 1.2.1.

**Comment by rinrinne** [comment]
Will merge tomorrow.

**Comment by huaxings** [comment]
There was a discussion that the current master branch has compatibility issues with Gerrit Plugin API 2.11-SNAPSHOT, which is currently unofficial. If the API interfaces provided by 2.11-SNAPSHOT becomes official and permanent, are you going to make the master branch to be compatible with the latest official API, or, both the latest and previous API's?
Thank you in advance.

**Comment by rinrinne** [comment]
If 2.11 is released, `master` branch would follow it. But unfortunately BC cannot be kept. Because expected interface class is disappeared.

So `master` branch will give up support against 2.8-2.10 API.

**Comment by rinrinne** [comment]
Merged.
