### ISSUE TITLE
Upload a new release

### ISSUE THREAD

**Issue by StephenKing** [rinrinne/gerrit-rabbitmq-plugin#12]
Thanks for that great plugin! We're currently testing this on https://review.typo3.org and it works very well.

One thing however: the last release is already pretty old and e.g. has `jar` as plugin name. Maybe you could upload a new one.

Thanks
Steffen

**Comment by rinrinne** [comment]
OK, I will release soon:)

**Comment by rinrinne** [comment]
Done.
https://github.com/rinrinne/gerrit-rabbitmq-plugin/releases/tag/rabbitmq-2.0

**Comment by StephenKing** [comment]
Thanks!

Btw. AFAIK you don't have to build against plugin API versions of patch level releases. Building against 2.8, 2.9 etc. should be fine (and from [recent postings on the repo-discuss list](https://groups.google.com/forum/#!topic/repo-discuss/nKZkbGjkskM) it looks like 2.10 is the first release that really changes API)

**Comment by rinrinne** [comment]
Yes, I already know that. But unfortunately it has not been documented. It means that it is only community rule. Just in case, I released packages for each API versions.

**Comment by rinrinne** [comment]
Closed.
